### ISSUE TITLE
Does not convert 9 meters to feet accuratly

### ISSUE THREAD

**Issue by NSWIDER** [ben-ng/convert-units#153]
this library converts 9 meters to 96.8751

it should convert 9 meters to 96.8751999504

**Comment by NSWIDER** [comment]
nm

**Comment by courdek** [comment]
@NSWIDER what happened? I'm also experiencing some weirdness converting meters to feet (and back), but in my case the issue is focused around multiples of 7 ft. 

`7` Feet converts to `2.133599931724802` meters
and then
`2.133599931724802` meters converts to `6.9999999999999` feet

**Comment by courdek** [comment]
nm

hahaha.

For posterity if anyone comes looking here, be sure to check whether or not you're using `ft` or `ft-us`
