### ISSUE TITLE
Upgrade Test Runner

### ISSUE THREAD

**Issue by Taar** [ben-ng/convert-units#180]
I believe this project would benefit from using a more modern test runner.

Requirements the test runner should support:
- Test coverage
- Features that make writing new tests easier (eg. watch mode, good docs, etc)
- Async test execution (Maybe this is more of a "nice-to-have" thing?)
- Typescript support

I've used [AVA](https://github.com/avajs/ava) is the past and I think it would be a good fit. What does everyone else think?

This issue is related to #179

**Comment by dmbarry86** [comment]
How set are you on using AVA here? My normal go to would be Jest and I think it handles your requirements but I'm happy to use AVA if you would prefer.

**Comment by Taar** [comment]
> 
> 
> How set are you on using AVA here? My normal go to would be Jest and I think it handles your requirements but I'm happy to use AVA if you would prefer.

@dmbarry86 Sure! Let's go with Jest. Ultimately, you're the one doing the work on this. Therefore, I think it would be beneficial to the project if the tool you're implementing is something you're familiar with. Also from a personal note, I'm very happy to have the opportunity to learn a new testing tool 😄
