### ISSUE TITLE
Definition for Third Unit Set

### ISSUE THREAD

**Issue by eimg** [ben-ng/convert-units#21]
Very cool library. I am trying to use this to build a traditional conversion app. 

Length for example, I like to add third unit set, let's call it "Burmese" length. So, there will be 3 sets of unit definitions for length: Metric, Imperial and Burmese. I would like to be able to convert between Metric <=> Imperial, Metric <=> Burmese and Imperial <=> Burmese.

Is there any way to achieve that?

**Comment by eimg** [comment]
Sorry that I overlooked. I can simply put additional units into existing set instead of adding new unit set.

**Comment by ben-ng** [comment]
Sorry I didn't see this earlier, send me a PR if you do implement additional units!
