### ISSUE TITLE
length.js imperial unit in

### ISSUE THREAD

**Issue by wardsng** [ben-ng/convert-units#3]
Cool library! I'm trying to do some conversions in IE8 and it's barfing on the 'in' key (due to being a keyword) in lib/definitions/length.js. Would you be able to stringify that key so it works?

Thanks!

**Comment by ben-ng** [comment]
Oops, sorry about that. I don't have time to maintain this lib right now, can you send me a PR?

**Comment by wardsng** [comment]
Sure, submitted a PR

**Comment by ben-ng** [comment]
Thanks, pushed in 0.1.1
