### ISSUE TITLE
convert from metric to imperial

### ISSUE THREAD

**Issue by bahodirk** [ben-ng/convert-units#55]
Hello, I have inputs only in metrics, I am trying to convert it to corresponding imperial unit in Angular 2 app.

For example, I am looking for 

`convert(1000).from('kg').toBest().imperial()`

**Comment by ben-ng** [comment]
There isn't a great way to do this yet, but this should work:

```
var metricUnits = convert().list('length').filter(function (unit) {
  return unit.system == 'metric';
});
convert(1200).from('mm').toBest({exclude: metricUnits})
```

**Comment by pedro-mass** [comment]
Could this be a feature? A lot of my unit conversions are from one system to the next, so I'd have to make a common function to handle this filter/lookup.

It would be nice if it was rolled into this awesome library.

**Comment by wootwoot1234** [comment]
+1
