### ISSUE TITLE
ClientSide usage

### ISSUE THREAD

**Issue by boyana86** [ben-ng/convert-units#72]
Hi,
First of all, thank you for your effort.
I would like to ask how I can use this js in frontend rather than backend?

**Comment by messinmotion** [comment]
Also interested

**Comment by cwalv** [comment]
@boyana86 you need to use a bundler that understands commonjs, like webpack.

**Comment by jiminikiz** [comment]
Already have this working on the front-end with webpack.

**Comment by PassTheMayo** [comment]
@jiminikiz Would you like to share how? I tried using browserify and webpack but I keep receiving the error `require is not defined`....

**Comment by jiminikiz** [comment]
I am using `vue-js` via the `cli` and I am able to `import` `convert-units` no problem. Not sure how to do it manually.

**Comment by jiminikiz** [comment]
I may do a webpack right up for how to do this, but for many using bundlers and webpack, this is a non-issue. Closing for now since there are solutions for this.
