### ISSUE TITLE
All the singular and plural values in description are first case except tonne

### ISSUE THREAD

**Issue by hosseintalebi** [ben-ng/convert-units#81]
I noticed the first letter of all the singular and plural values in description for mass units are capital except for `convert().describe('t')` which returns them in lowercase:
```
{
abbr:"t",
measure:"mass",
system:"metric",
singular:"tonne",
plural:"tonnes"
} 
```
Any reasons for that?

**Comment by jiminikiz** [comment]
This has been fixed with #85. Version 2.3.2 resolves this issue. Working on publishing to npm.
