### ISSUE TITLE
Best unit function

### ISSUE THREAD

**Issue by maddijoyce** [ben-ng/convert-units#9]
Hey,

I've just made a pull request for some additional units.
In my forked version, I've also added a 'best' function.

So you run:
```javascript
convert(1200).from('mm').best()
```

And it will choose the best units (in this case meters) with the logic of highest units where the number is greater than 1.

Do you want a pull request for that?

**Comment by ben-ng** [comment]
Sounds like a useful addition!

**Comment by toddself** [comment]
Hi @maddijoyce I just merged most of your original PR except for the `best` functionality.

Would you want to make a clean PR with just that functionality?

**Comment by maddijoyce** [comment]
Sorry, completely forgot to do this.
I've added a new PR #15 off the current master branch (0.4.0 I think).

Cheers,
Maddi

**Comment by maddijoyce** [comment]
Messed up the case in the tests again. I've done it properly with #16.
