### ISSUE TITLE
Client side usage

### ISSUE THREAD

**Issue by awps** [ben-ng/convert-units#94]
As noted here https://github.com/ben-ng/convert-units/issues/53

I want to use it in the browser but no success. How to do it?

I did this:
```
browserify node_modules/convert-units/lib/index.js -o assets/convert-units-dist.js
```

Now I have `convert-units-dist.js` in `assets` folder. I included the script in the page and what's next? 
I tried the following with no success:
```js
convert(1).from('l').to('ml'); // Fail
Converter(1).from('l').to('ml'); // Fail
```
Looks like the browserify does nothing than just bundling all the scripts together but...

Any help is appreciated.

**Comment by ben-ng** [comment]
You need to use the `--standalone` or `-s` option.
